### PR TITLE
Fix order on which we display microbenchmark results

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This pull request fixes the rendering of microbenchmark results by reordering the column properly.

### CODE REVIEW

**Comment by GuptaManan100** [comment]
What! we were displaying results in the incorrect order?

**Comment by frouioui** [comment]
> What! we were displaying results in the incorrect order?

Just found out, yes. Fixed the way we compute the difference and how we render the different values. Mostly, the two cols (ref and cmp) got mixed up

**Comment by GuptaManan100** [comment]
You might need to update the tests too, reflect the changes there

**Review by GuptaManan100 — APPROVED** [review]
LGTM 🔎

**Pull request merged**
