### PR TITLE
Built basic cli commands and created in docs cli.md

### PR DESCRIPTION
**Pull request by Akilan1999**
# Command line interface

## Describes the cli commands to use:
The implementation can be found on cli.py:
1. When running any OLTP or TPCC the source and commit hash must be provided

### Sample run
```
./cli --run-all -c HEAD -s api_call
```

#### Run both OLTP and TPCC benchmarks
```
--run-all
```

#### Run TPCC
```
--run-tpcc or -runt
```

#### Run OLTP
```
--run-oltp or -runo
```

#### Provide Inventory file to run
If not provided the inventory file provided in config.yaml will be called by1 default.
```
--inventory-file=<inventory file name> or -invf=<inventory file name>
```

#### To Specify commit hash or branch name
```
--commit <commit hash or branch name> or -c <commit hash or branch name>
```

#### Source
To specify from which source the benchmark is called from. This is
added as a tag in mysql database where the benchmark run results are stored.

```
//Example of source name: Api_call,Webhook,test_call
--source <source name> or -s <source name>
```

### CODE REVIEW

**Review by frouioui — CHANGES_REQUESTED** [review]
We should remove the following file: [.DS_Store](https://github.com/vitessio/arewefastyet/blob/d4ff99c6ab2539697ad800f246ce20a3e510450d/.DS_Store) and add it to the `.gitignore`.

**Comment by Akilan1999** [comment]
> We should remove the following file: [.DS_Store](https://github.com/vitessio/arewefastyet/blob/d4ff99c6ab2539697ad800f246ce20a3e510450d/.DS_Store) and add it to the `.gitignore`.

Working on it

**Review by frouioui — APPROVED** [review]
Looks good!

**Comment by Akilan1999** [comment]
> Looks good!

Are you going to merge it

**Pull request merged**
