### PR TITLE
Adding types in SearchPage

### PR DESCRIPTION
**Pull request by DhairyaMajmudar**
Search Page files were throwing type errors since the  types were not defined which are now resolved by adding relevant types to  the files. 

Files Changed:
1. `website/src/pages/SearchPage/components/Hero.tsx`
2. `website/src/pages/SearchPage/components/SearchMacro.tsx`

### CODE REVIEW

**Comment by DhairyaMajmudar** [comment]
> PR is already there resolving it #529

Yeah, this PR is more focused on resolving the type errors coming from the props of several data types.

**Review by frouioui — APPROVED** [review]
This looks good to me. Eventually we should do something similar for all functions and props.

**Comment by frouioui** [comment]
Thank you for the contribution 🙇🏻

**Comment by DhairyaMajmudar** [comment]
> This looks good to me. Eventually we should do something similar for all functions and props.

I see, will look into this and soon open a PR : )

**Pull request merged**
